export function getProductsinSeason() {
  return [
    {
      id: 1,
      title: "Tomatoes",
      pricecut: 15,
      newprice: 1000,
      oldprice: 3000,
      image: "/images/tomatoseason.jpg",
    },
    {
      id: 2,
      title: "Shrimps",
      pricecut: 15,
      newprice: 1000,
      oldprice: 2500,
      image: "/images/shrimpseason.jpg",
    },
    {
      id: 3,
      title: "Snail",
      pricecut: 15,
      newprice: 1000,
      oldprice: 2500,
      image: "/images/snailseason.jpg",
    },
    {
      id: 4,
      title: "Pepper",
      pricecut: 15,
      newprice: 1000,
      oldprice: 2500,
      image: "/images/chilipepper.jpg",
    },
    {
      id: 5,
      title: "Cat Fish",
      pricecut: 15,
      newprice: 1000,
      oldprice: 3000,
      image: "/images/catfish.jpg",
    },
    {
      id: 6,
      title: "Soya Beans",
      pricecut: 15,
      newprice: 1000,
      oldprice: 3000,
      image: "/images/soya beanseason.jpg",
    },
    {
      id: 7,
      title: "Orange",
      pricecut: 15,
      newprice: 1000,
      oldprice: 3000,
      image: "/images/orangeseason.jpg",
    },
    {
      id: 8,
      title: "Paw Paw",
      pricecut: 15,
      newprice: 1000,
      oldprice: 3000,
      image: "/images/pawpaw.jpg",
    },
  ];
}
