const products = [
  {
    id: 1,
    title: "Orange",
    category: { id: 1, name: "Fruits" },
    quantity: 1,
    image: "/images/orangeproduct.jpg",
  },
  {
    id: 2,
    title: "Grape",
    category: { id: 1, name: "Fruits" },
    quantity: 3,
    image: "/images/grape.jpg",
  },
  {
    id: 3,
    title: "Carrot",
    category: { id: 1, name: "Fruits" },
    quantity: 9,
    image: "/images/carrot.jpg",
  },

  {
    id: 4,
    title: "Cucumber",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/cucumber.jpg",
  },
  {
    id: 5,
    title: "Water melon",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/watermelon.jpg",
  },
  {
    id: 6,
    title: "Banana",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/banana.jpg",
  },
  {
    id: 7,
    title: "Mango",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/mango.jpg",
  },
  {
    id: 8,
    title: "Pineapple",
    category: { id: 1, name: "Fruits" },
    quantity: 3,
    image: "/images/pineapple.jpg",
  },
  {
    id: 9,
    title: "Cashew",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/cashews.jpg",
  },
  {
    id: 10,
    title: "Lemon",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/lemonproduct.jpg",
  },

  {
    id: 12,
    title: "Paw-Paw",
    category: { id: 1, name: "Fruits" },
    quantity: 5,
    image: "/images/pawpaw.jpg",
  },
  {
    id: 13,
    title: "Spinach",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/spinach.jpg",
  },
  {
    id: 14,
    title: "Brocolli",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/brocolli.jpg",
  },
  {
    id: 15,
    title: "tomatoes",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/tomatos.jpg",
  },
  {
    id: 16,
    title: "Pepper",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/pepper.jpg",
  },
  {
    id: 17,
    title: "Cabbage",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/cabbages.jpg",
  },
  {
    id: 18,
    title: "Chilli Pepper",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/chilipepper.jpg",
  },
  {
    id: 19,
    title: "Green Beans",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/green beans.jpg",
  },
  {
    id: 20,
    title: "Garden egg",
    category: { id: 2, name: "Vegetables" },
    quantity: 5,
    image: "/images/gardenegg.jpg",
  },
  {
    id: 21,
    title: "Blackeye Beans",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/blackeye.jpg",
  },
  {
    id: 22,
    title: "Soya Beans",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/soya beans.jpg",
  },
  {
    id: 23,
    title: "Bambara nut",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/bambara.jpg",
  },
  {
    id: 24,
    title: "Green Peas",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/green peas.jpg",
  },
  {
    id: 25,
    title: "Brown Beans",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/brownbeans.jpg",
  },
  {
    id: 26,
    title: "Honey Beans",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/honeybeans.jpg",
  },
  {
    id: 27,
    title: "Bread Fruit",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/breadfruit.jpg",
  },
  {
    id: 28,
    title: "Cowpea",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/soya beans.jpg",
  },
  {
    id: 29,
    title: "Groundnut",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/groundnut.jpg",
  },
  {
    id: 30,
    title: "Millet",
    category: { id: 3, name: "Legumes" },
    quantity: 5,
    image: "/images/millet.jpg",
  },
  {
    id: 31,
    title: "Shrimps",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/shrimps.jpg",
  },
  {
    id: 32,
    title: "Oyester",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/oyester.jpg",
  },
  {
    id: 33,
    title: "Cat Fish",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/catfish.jpg",
  },
  {
    id: 34,
    title: "Cray Fish",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/crayfish.jpg",
  },
  {
    id: 35,
    title: "Octopus",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/soyabeans.jpg",
  },
  {
    id: 36,
    title: "Fish",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/fish.jpg",
  },
  {
    id: 37,
    title: "A Fish",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
  },
  {
    id: 38,
    title: "Periwinkle",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/periwinkle.jpg",
  },
  {
    id: 39,
    title: "Water Snail",
    category: { id: 4, name: "Sea Foods" },
    quantity: 5,
    image: "/images/watersnail.jpg",
  },
  {
    id: 40,
    title: "Beef/Cow Meat",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/meat.jpg",
  },

  {
    id: 42,
    title: "Mutton/Sheep Meat",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/mutton.jpg",
  },
  {
    id: 43,
    title: "Chevron/Goat Meat",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/chevron.jpg",
  },
  {
    id: 45,
    title: "Pork/Pig Meat",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/pork.jpg",
  },
  {
    id: 46,
    title: "Chicken",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/chickenmeat.jpg",
  },
  {
    id: 47,
    title: "Turkey",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/turkeymeat.jpg",
  },
  {
    id: 48,
    title: "Snail",
    category: { id: 5, name: "Meats" },
    quantity: 5,
    image: "/images/snail.jpg",
  },
  {
    id: 49,
    title: "Cow",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/cow.jpg",
  },
  {
    id: 50,
    title: "Goat",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/goat.jpg",
  },
  {
    id: 51,
    title: "Sheep",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/sheep.jpg",
  },
  {
    id: 52,
    title: "Pig",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/pig.jpg",
  },
  {
    id: 53,
    title: "Chicken",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/chicken.jpg",
  },
  {
    id: 54,
    title: "Turkey",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/turkey.jpg",
  },
  {
    id: 55,
    title: "Rabbit",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/rabbit.jpg",
  },
  {
    id: 56,
    title: "Snail",
    category: { id: 6, name: "Live Stock" },
    quantity: 5,
    image: "/images/snail.jpg",
  },
];

export function getProducts() {
  return products;
}
